services:

  frontend:
    build: ./frontend
    container_name: rag-f1-frontend
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend
    networks:
      - fe-be

  backend:
    build: ./backend
    container_name: rag-f1-backend
    restart: always
    env_file:
      - ../.env
    depends_on:
      - qdrant
    networks:
      - fe-be
      - be-db

  qdrant:
    image: qdrant/qdrant:v1.18.0
    container_name: rag-f1-qdrant
    restart: always
    volumes:
      - ../data/qdrant_storage:/qdrant/storage
    networks:
      - be-db


networks:
  fe-be:
  be-db: